/**
 * @author group100 (19094184, 19088716)
 */
package virtualpetgame.GUIs;

import javax.swing.JButton;
import virtualpetgame.Game;

public class LoadMenu extends javax.swing.JFrame implements GetWaitButton, GetOption{

    Game game; //main game controller object
    
    @Override
    public JButton getWaitButton() {
        return this.continueButton;
    }
    
    /**
     * Returns the index of the selected item
     * 
     * @return a number relative to the index in the list
     */
    @Override
    public String getOption() {
        return Integer.toString(this.fileSelectionComboBox.getSelectedIndex());
    }
    
    /**
     * Creates new form LoadMenu
     */
    public LoadMenu(Game game) {
        this.game = game;
        initComponents();
        GUIutils.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseFileLabel = new javax.swing.JLabel();
        fileSelectionComboBox = new javax.swing.JComboBox<>();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseFileLabel.setText("Choose a file to load:");

        fileSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(this.game.fileIO.getFormattedFileList().toArray(new String[0])));

        continueButton.setText("OK");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(continueButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseFileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFileLabel)
                    .addComponent(fileSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(continueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Once the user continues, notify whatever is waiting for this menu.
     */
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        synchronized(continueButton) {
            continueButton.notify();
        }
        this.dispose();
    }//GEN-LAST:event_continueButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseFileLabel;
    private javax.swing.JButton continueButton;
    private javax.swing.JComboBox<String> fileSelectionComboBox;
    // End of variables declaration//GEN-END:variables
}
