/**
 * @author group100 (19094184, 19088716)
 */
package virtualpetgame.GUIs;

import javax.swing.JOptionPane;
import virtualpetgame.ActivePet;
import virtualpetgame.Game;

public class MainGame extends javax.swing.JFrame {

    private final Game game;

    /**
     * Creates new form MainGame
     */
    public MainGame(Game game) {
        this.game = game;
        initComponents();
        GUIutils.centerWindow(this);
    }

    /**
     * Sets the art to display in the art box
     *
     * @param art a String to print into the box
     */
    public void setArt(String art) {
        this.petArtTextArea.setText(art);
    }

    /**
     * Sets the value of the hunger bar
     *
     * @param percentage an int from 0 - 100
     */
    public void setHunger(int percentage) {
        this.hungerBar.setValue(percentage);
    }

    /**
     * Sets the value of the boredom bar
     *
     * @param percentage an int from 0 - 100
     */
    public void setBoredom(int percentage) {
        this.boredomBar.setValue(percentage);
    }

    /**
     * Sets the value of the cleanliness bar
     *
     * @param percentage an int from 0 - 100
     */
    public void setCleanliness(int percentage) {
        this.cleanlinessBar.setValue(percentage);
    }

    /**
     * Sets the text to show as the pets mood
     *
     * @param mood a String containing the mood text
     */
    public void setMood(String mood) {
        this.moodTextField.setText(mood);
    }

    /**
     * Sets the money value to display
     *
     * @param money an int value of money to display
     */
    public void setMoney(int money) {
        this.moneyBar.setText("$" + Integer.toString(money));
    }

    /**
     * Carries out any tick events the GUI might be waiting for
     */
    public void tick() {
        this.checkErrorMessage();
    }

    /**
     * Shows the death dialog, and disposes of the frame. Should only be called
     * when the game is shutting down.
     */
    public void showDeathDialog() {
        JOptionPane.showMessageDialog(this,
                "Your pet has died!\n"
                + "Your save will be deleted automatically.",
                "Oh no!",
                JOptionPane.WARNING_MESSAGE);
        this.dispose();
    }

    /**
     * Shows the help dialog box
     */
    private void showHelpDialog() {
        JOptionPane.showMessageDialog(this,
                "How to play:\n"
                + "Feed, play with, or clean your pet to keep them happy.\n"
                + "Try to keep hunger and boredom low, and cleanliness high.\n"
                + "The happier your pet is, the more money you earn.\n"
                + "The game will save automatically every minute, as well as saving on close.\n"
                + "Make sure to care for your pet well!\n",
                "Help",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Prints some error text in red, into the game window
     *
     * @param text a String to print
     */
    private void showErrorText(String text) {
        this.errorMessageLabel.setText(text);
        this.errorMessageLabel.setEnabled(true);
    }

    //timeout counter we can use to track the ticks
    private int errorTimeoutCount;

    /**
     * Waits for the GUI to be ticked, and if 5 ticks have passed, clears the
     * error message.
     */
    private void checkErrorMessage() {
        if (!this.errorMessageLabel.getText().equals("")) {
            if (++errorTimeoutCount > 5) {
                errorTimeoutCount = 0;
                this.showErrorText("");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        petArtTextArea = new javax.swing.JTextArea();
        hungerLabel = new javax.swing.JLabel();
        hungerBar = new javax.swing.JProgressBar();
        boredomLabel = new javax.swing.JLabel();
        boredomBar = new javax.swing.JProgressBar();
        cleanlinessLabel = new javax.swing.JLabel();
        cleanlinessBar = new javax.swing.JProgressBar();
        moneyLabel = new javax.swing.JLabel();
        moneyBar = new javax.swing.JTextField();
        playButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        feedButton = new javax.swing.JButton();
        moodLabel = new javax.swing.JLabel();
        moodTextField = new javax.swing.JTextField();
        errorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                gameExiting(evt);
            }
        });

        petArtTextArea.setEditable(false);
        petArtTextArea.setColumns(20);
        petArtTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        petArtTextArea.setRows(5);
        jScrollPane1.setViewportView(petArtTextArea);

        hungerLabel.setText("Hunger:");

        boredomLabel.setText("Boredom:");

        cleanlinessLabel.setText("Cleanliness:");

        moneyLabel.setText("Money:");

        moneyBar.setEditable(false);
        moneyBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyBarActionPerformed(evt);
            }
        });

        playButton.setText("Play (" + ((ActivePet.PLAY_COST == 0) ? "Free" : "$" + ActivePet.PLAY_COST) + ")");
        playButton.setToolTipText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        cleanButton.setText("Clean (" + ((ActivePet.CLEAN_COST == 0) ? "Free" : "$" + ActivePet.CLEAN_COST) + ")");
        cleanButton.setToolTipText("Clean");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        helpButton.setText("?");
        helpButton.setToolTipText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        feedButton.setText("Feed (" + ((ActivePet.FEED_COST == 0) ? "Free" : "$" + ActivePet.FEED_COST) + ")");
        feedButton.setToolTipText("Feed");
        feedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedButtonActionPerformed(evt);
            }
        });

        moodLabel.setText("Mood:");

        moodTextField.setEditable(false);
        moodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodTextFieldActionPerformed(evt);
            }
        });

        errorMessageLabel.setForeground(new java.awt.Color(255, 30, 30));
        errorMessageLabel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(feedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hungerBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boredomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cleanlinessBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moneyBar)
                    .addComponent(moodTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hungerLabel)
                            .addComponent(boredomLabel)
                            .addComponent(cleanlinessLabel)
                            .addComponent(moneyLabel)
                            .addComponent(moodLabel))
                        .addGap(0, 292, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorMessageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hungerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boredomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boredomBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanlinessLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanlinessBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playButton)
                            .addComponent(cleanButton)
                            .addComponent(feedButton)
                            .addComponent(helpButton)
                            .addComponent(errorMessageLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moneyBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyBarActionPerformed
        //Does nothing
    }//GEN-LAST:event_moneyBarActionPerformed

    /**
     * Shows the help dialog
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        this.showHelpDialog();
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * If the user can afford it, plays with the pet
     */
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        if (game.activePet.getMoney() < ActivePet.PLAY_COST) {
            this.showErrorText("You can't afford that!");
        } else {
            game.activePet.spend(ActivePet.PLAY_COST);
            game.activePet.play();
            game.updateGUI();
        }
    }//GEN-LAST:event_playButtonActionPerformed

    /**
     * If the user can afford it, cleans the pet
     */
    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        if (game.activePet.getMoney() < ActivePet.CLEAN_COST) {
            this.showErrorText("You can't afford that!");
        } else {
            game.activePet.spend(ActivePet.CLEAN_COST);
            game.activePet.clean();
            game.updateGUI();
        }
    }//GEN-LAST:event_cleanButtonActionPerformed

    /**
     * If the user can afford it, feeds the pet
     */
    private void feedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedButtonActionPerformed
        if (game.activePet.getMoney() < ActivePet.FEED_COST) {
            this.showErrorText("You can't afford that!");
        } else {
            game.activePet.spend(ActivePet.FEED_COST);
            game.activePet.feed();
            game.updateGUI();
        }
    }//GEN-LAST:event_feedButtonActionPerformed

    private void moodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodTextFieldActionPerformed
        //Does nothing
    }//GEN-LAST:event_moodTextFieldActionPerformed

    /**
     *  Makes sure the game gets saved if the window is closing
     */
    private void gameExiting(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_gameExiting
        game.fileIO.save();
    }//GEN-LAST:event_gameExiting

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar boredomBar;
    private javax.swing.JLabel boredomLabel;
    private javax.swing.JButton cleanButton;
    private javax.swing.JProgressBar cleanlinessBar;
    private javax.swing.JLabel cleanlinessLabel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton feedButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JProgressBar hungerBar;
    private javax.swing.JLabel hungerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moneyBar;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel moodLabel;
    private javax.swing.JTextField moodTextField;
    private javax.swing.JTextArea petArtTextArea;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
